### ISSUE TITLE
Look into writing PHPUnit tests

### ISSUE THREAD

**Issue by neoncitylights** [neoncitylights/StructuredNavigation#7]

**Comment by SamanthaNguyen** [comment]
So this task is meant to be "look into PHPUnit" basically; I did a bit of research and some testing locally of writing a basic test for the service wiring and \StructuredNavigation\Services. My conclusion is that PHPUnit is quite nice and useful; I'll publish thePHPUnit tests tomorrow and make sure Travis CI runs the tests automatically, then close this task. After that I'll keep writing more tests as I find time to do so 😄

**Comment by SamanthaNguyen** [comment]
I'm going to hold this task off until this weekend. Since this is a PHP 7.1+ project, it seems like there might be a conflict with MediaWiki and using PHPUnit 7 for the project. I'll also need to setup Travis CI a little bit more so that it git clones MW core for each build. I did test out with PHPUnit 6.5.13 and my service test ran fine locally, but I'll need to double-check everything when the weekend comes around.
